#!/bin/bash

export PATH="$MISC_ROOT:$PATH"

source "$MISC_ROOT/prompt"
init_prompt

export LSCOLORS=gxBxhxDxfxhxhxhxhxcxcx
alias ll='ls -alGh'

alias prettyjson='python -m json.tool'

function grepdir() {
    grep -lr "$1" .
}

function img() {
    sips --getProperty pixelWidth --getProperty pixelHeight $1
}

function branch() {
    echo $(git rev-parse --abbrev-ref HEAD 2> /dev/null)
}

function typeof() {
    echo ${(tP)1}
}

export PATH="/Applications/Sublime Text 2.app/Contents/SharedSupport/bin/:$PATH"
export PATH="/Applications/Sublime Text 3.app/Contents/SharedSupport/bin/:$PATH"
export PATH="/Applications/Sublime Text.app/Contents/SharedSupport/bin/:$PATH"

