#!/bin/bash

function init_prompt() {
    export PROMPT_COMMAND=update_prompt
}

# Sets the prompt with the current directory, git branch and git status
function update_prompt() {
    local host=${HOSTNAME%.local}
    local user=$USER

    local reset="\[\e[0m\]"

    local repo=$(git rev-parse --show-toplevel 2> /dev/null)
    if [[ ! -z "$repo" ]]; then
        local red='\[\e[31m\]'
        local green='\[\e[32m\]'
        local yellow='\[\e[33m\]'
    
        local branch='HEAD'
        if [[ ! -z $(git branch) ]]; then
            # Get the current branch name or use "HEAD" if repo is newly initialized
            branch=$(git rev-parse --abbrev-ref HEAD)
        fi
        local stat=$(git status --porcelain)

        local warn=$green
        if [[ ! -z $(echo "$stat" | cut -c1-2 | grep 'U') ]]; then
            # Contains conflicts
            warn=$red
        elif [[ ! -z "$stat" ]]; then
            # Contains modifications
            warn=$yellow
        fi
        
        local base=$(basename "$repo")
        local path=$(echo "${PWD#$repo}")

        export PS1="${host}:${reset}${base}${warn}(${branch})${reset}${path} ${user}\$${reset} "
    else
        local path=$PWD
        if [[ "$path" =~ ^"$HOME"(/|$) ]]; then
            path="~${path#$HOME}"
        fi
        
        export PS1="${host}:${reset}${path} ${user}\$${reset} "
    fi
}

